title: CSCI 1210 - Prof Haas' Class Resources

plugins:
  - jekyll-remote-theme

remote_theme: broccolini/swiss
theme_color: blue

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: "custom_post"
